### ISSUE TITLE
Pre-Compressed file support?

### ISSUE THREAD

**Issue by sfranzyshen** [PierreQuentel/httpcompressionserver#1]
It's clear to me this package handles the file compression automatically ... is it possible to handle Pre-Compressed files? My final (deployment) target already handles serving pre-compressed files and i'm trying to mimic this function within my development environment.

> when the client ask for a file and it's not found by the url ... it then checks to see if there is a pre-compressed version (file.html.gz) of the file ... adds the compressed header and then send the compressed file as the asked for url ...

Thank You

BTW this feature is available in production servers ... Apache

**Comment by PierreQuentel** [comment]
A file is compressed only if its type is inside a list, set by default to the value of `commonly_compressed_types` in the script. Files types are deducted from their extension.

The type of a pre-compressed file (with an extension such as .zip, .gz, .tar.gz, etc.) is not in this list, so these files are not compressed a second time, they are served "as is".

**Comment by sfranzyshen** [comment]
Thank you for your response ... I guess the simplest answer to my question is "No" your package does not (and perhaps will never) support "PRE-compressed" files ... lucky for me (and anyone else looking for this feature) there is already another package that does handle "Pre-compressed" files ... https://github.com/dkarmalita/http-serve
